
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uurlcverrumsmxdpblau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cmxjdmVycnVtc214ZHBibGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDE4MzksImV4cCI6MjA2MDU3NzgzOX0.XqkKaAhjFd86lA04sEdmgRlZ8g7tpG94lSBq9maQgkc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
